# Generated by Django 2.2.14 on 2020-07-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_vhjfjf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='vhjfjf',
        ),
    ]
